FROM python:3.11-slim-bullseye

WORKDIR /app

RUN apt-get update && apt-get install -y git

RUN git clone https://github.com/ariez3/LunaNera.git .

COPY config.json /app/config.json

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

ENTRYPOINT ["python", "run.py"]
